steps:
  - command:
      - "go build"
    label: "\U0001F528 Build / :go: 1.11"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.11"
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - "go build"
    label: "\U0001F528 Build / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - "go get golang.org/x/lint/golint"
      - "go get github.com/fzipp/gocyclo"
      - "./scripts/lint.sh"
    label: "\U0001F9F9 Run tests and linting"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - "go build"
      - "./.buildkite/run-coverage.sh"
    label: "\U0001F456 Computing coverage / :go: 1.12"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.12"
          propagate-environment: true
          environment: ["COVERALLS_TOKEN"]
    retry:
      automatic:
        - exit_status: 128
          limit: 3
